"""Shared helpers for integration tests."""

from __future__ import annotations

import contextlib
import io
from typing import Iterator

from create_dlthub_workspace.scaffold import PER_AGENT_DIR, SCAFFOLDS_DIR


@contextlib.contextmanager
def silenced() -> Iterator[None]:
    """Suppress stdout + stderr noise from rich.console panels during tests."""
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        yield


def scaffold_has_ai_files(scaffold: str = "starter_workspace") -> bool:
    """True iff the bundled scaffold already includes the AI workbench files.

    AI files are generated by `make generate-ai` and committed into
    `_agents/<agent>/`. Until that's been done, e2e tests that assert on AI
    file presence skip with a hint.
    """
    return (SCAFFOLDS_DIR / scaffold / PER_AGENT_DIR).is_dir()


# Files we expect to find at the workspace root after assembling each agent,
# so individual tests can assert the selected agent is present and others are
# filtered out. `.agents/` is codex-only.
EXPECTED_AGENT_ROOT_ENTRIES: dict[str, tuple[str, ...]] = {
    "claude": (".claude", ".claudeignore", ".mcp.json"),
    "cursor": (".cursor", ".cursorignore"),
    "codex": (".codex", ".codexignore", "AGENTS.md", ".agents"),
}
